apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ivx0cfsus-nodejs 
  janus-idp.io/tekton: ivx0cfsus-nodejs
  backstage.io/kubernetes-id: ivx0cfsus-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ivx0cfsus-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml