apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ivx0cfsus-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ivx0cfsus-nodejs 
  name: ivx0cfsus-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ivx0cfsus-nodejs 
